#! /bin/bash

virt-install \
--name centos7 \
--ram 1024 \
--disk path=/var/lib/kvmbld/images/centos-7/centos7.qcow2,size=8 \
--vcpus 1 \
--os-type linux \
--graphics none \
--console pty,target_type=serial \
--location 'http://mirror.i3d.net/pub/centos/7/os/x86_64/' \
--extra-args 'console=ttyS0,115200n8 serial'
