USE mysql;
CREATE USER '<REMUSER>'@'localhost' IDENTIFIED BY '<REMUSERPSW>';
CREATE USER '<REMUSER>'@'%' IDENTIFIED BY '<REMUSERPSW>';
GRANT ALL ON *.* TO '<REMUSER>'@'localhost';
GRANT ALL ON *.* TO '<REMUSER>'@'%';


